# Generated by Django 6.0.7 on 2026-07-14 03:52

import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('VEG', 'Vegetarian'), ('RAW', 'Raw Fish'), ('COOKED', 'Cooked Fish'), ('POKE', 'Poke Bowl'), ('HARU', 'Harumaki')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop='middle', force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[800, 800], upload_to='products/')),
                ('is_available', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('spice_level', models.IntegerField(choices=[(0, 'No Spice'), (1, 'Mild'), (2, 'Medium'), (3, 'Hot')], default=0)),
                ('allergens', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
